theme: jekyll-theme-minimal
lang: ja
google_tag_manager: GTM-WFQ64LJ
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: 3594t-deck/index.html
    values:
      sitemap: false
url: 'https://boushi-bird.github.io'
